# External Secrets Operator — valores customizados
# Helm chart: https://charts.external-secrets.io | chart: external-secrets
# Verificar versão mais recente: helm search repo external-secrets/external-secrets

installCRDs: true

replicaCount: 2

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

webhook:
  replicaCount: 2
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

certController:
  replicaCount: 1
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
